# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: tye-talk-11-multi-repo
extensions:
- name: zipkin
- name: elastic
  logPath: ./.logs
services:
- name: api-book
  project: api.books/api.books.csproj
# MySQL
# Adminer info: host.docker.internal:23306
- name: mysql-jamilious
  image: mysql
  bindings:
  - connectionString: Server=${host};Port=${port};Database=Jamilious;User ID=${env:MYSQL_USER};Password=${env:MYSQL_PASSWORD}
    containerPort: 3306
    port: 23306 # Uncomment this line to run with a static external port
  env:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_USER=mysql
  - MYSQL_PASSWORD=password    
  - MYSQL_DATABASE=Jamilious
# Uncomment the following lines to make storage persistent across runs
  volumes:
  - name: mysql-jamilious
    target: /var/lib/mysql
# Database Web Admin
- name: adminer
  image: adminer
  bindings:
  - protocol: http
    containerPort: 8080
    port: 25480 # Uncomment this line to run with a static external port
# Redis
- name: redis
  image: redis
  bindings:
  - port: 36379
    containerPort: 6379
    connectionString: "${host}:${port}" 
# Redis admin
- name: redis-commander
  image: rediscommander/redis-commander:latest
  bindings:
  - port: 38081
    protocol: http
    containerPort: 8081
  env:
  - REDIS_HOSTS=local:redis:6379